import { z } from 'zod';

const dateStr = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Data in formato YYYY-MM-DD');

export const dividendCreateSchema = z.object({
    assetTicker: z.string().trim().min(1, 'Ticker richiesto').max(40),
    assetIsin: z.string().trim().optional().nullable(),
    assetName: z.string().trim().optional().nullable(),
    exDate: dateStr,
    paymentDate: dateStr,
    dividendPerShare: z.number().positive('Dividendo per azione > 0'),
    quantity: z.number().nonnegative(),
    grossAmount: z.number().nonnegative(),
    taxAmount: z.number().nonnegative().default(0),
    netAmount: z.number().nonnegative(),
    currency: z.string().default('EUR'),
    grossAmountEur: z.number().nonnegative().optional().nullable(),
    netAmountEur: z.number().nonnegative().optional().nullable(),
    exchangeRate: z.number().positive().optional().nullable(),
    dividendType: z.enum(['ordinary', 'extraordinary', 'interim', 'final', 'coupon']).default('ordinary'),
    isAutoGenerated: z.boolean().default(false),
    costPerShare: z.number().nonnegative().optional().nullable(),
    notes: z.string().max(500).optional().nullable(),
});

export const dividendUpdateSchema = dividendCreateSchema.partial().extend({
    id: z.string().min(1),
});

export const dividendScrapeSchema = z.object({
    isin: z.string().trim().regex(/^[A-Z]{2}[A-Z0-9]{9}\d$/i, 'ISIN non valido'),
    ticker: z.string().trim().min(1),
    quantity: z.number().nonnegative(),
    assetName: z.string().trim().optional().nullable(),
    assetType: z.enum(['stock', 'etf', 'auto']).default('auto'),
    costPerShare: z.number().nonnegative().optional().nullable(),
});

export type DividendCreateInput = z.infer<typeof dividendCreateSchema>;
export type DividendUpdateInput = z.infer<typeof dividendUpdateSchema>;
export type DividendScrapeInput = z.infer<typeof dividendScrapeSchema>;
