import { z } from 'zod';

export const preferencesSchema = z.object({
    propertyPrice: z.number().min(0).optional(),
    downpayment: z.number().min(0).optional(),
    purchaseTaxes: z.number().min(0).optional(),
    notaryFees: z.number().min(0).optional(),
    agencyFees: z.number().min(0).optional(),
    netIncome: z.number().min(0).optional(),
    person1Name: z.string().max(100).optional(),
    person1Income: z.number().min(0).optional(),
    person2Name: z.string().max(100).optional(),
    person2Income: z.number().min(0).optional(),
    expensesList: z.string().optional(), // JSON string
    hasExistingLoan: z.boolean().optional(),
    knowsExistingInstallment: z.boolean().optional(),
    existingInstallment: z.number().min(0).optional(),
    existingRemainingCapital: z.number().min(0).optional(),
    existingRate: z.number().min(0).max(100).optional(),
    existingYearsLeft: z.number().min(0).optional(),
    rate: z.number().min(0).max(100).optional(),
    years: z.number().min(1).max(50).optional(),
    expectedRent: z.number().min(0).optional(),
    maintenanceTaxes: z.number().min(0).optional(),
    marketReturn: z.number().min(-100).max(100).optional(),
    vacancyRate: z.number().min(0).max(100).optional(),
    rentInflation: z.number().min(-50).max(50).optional(),
    extraMaintenance: z.number().min(0).optional(),
    realEstateList: z.string().optional(),
    existingLoansList: z.string().optional(),
    customStocksList: z.string().optional(),
    acceptedPurchases: z.string().optional(),
    careerProgression: z.string().optional(),
    salaryCalculationHistory: z.string().optional(),
    // FIRE
    birthYear: z.number().int().min(1900).max(2100).nullable().optional(),
    retirementAge: z.number().int().min(20).max(100).nullable().optional(),
    expectedMonthlyExpenses: z.number().min(0).nullable().optional(),
    monthlySavings: z.number().min(0).optional(),
    fireWithdrawalRate: z.number().min(0).max(100).optional(),
    fireExpectedReturn: z.number().min(-100).max(100).optional(),
    fireVolatility: z.number().min(0).max(100).optional(),
    expectedPublicPension: z.number().min(0).optional(),
    publicPensionAge: z.number().int().min(50).max(100).optional(),
    applyTaxStamp: z.boolean().optional(),
    includeIlliquidInFire: z.boolean().optional(),
    separateEmergencyFund: z.boolean().optional(),
    // Fondo Pensione Complementare
    enablePensionOptimizer: z.boolean().optional(),
    grossIncome: z.number().min(0).optional(),
    pensionContribution: z.number().min(0).max(5164.57).optional(),
    pensionFundAccessAge: z.number().int().min(50).max(100).optional(),
    pensionFundExitTaxRate: z.number().min(9).max(15).optional(),
    pensionExitMode: z.enum(["annuity", "hybrid"]).optional(),
    employerContributionType: z.enum(["percent", "fixed"]).optional(),
    employerContributionValue: z.number().min(0).optional(),
    // Budget
    budgetCategoriesList: z.string().optional(),
    budgetSettings: z.string().optional(),
    subscriptionsList: z.string().optional(),
    // AI
    aiUserProfile: z.string().max(8000).optional(),
});
