import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getAuthenticatedUserId, unauthorizedResponse, UnauthorizedError } from '@/lib/api-auth';
import { dividendScrapeSchema } from '@/lib/validations/dividends';
import {
    scrapeDividendsByIsin,
    calculateDividendTax,
    IT_DIVIDEND_WITHHOLDING_TAX,
} from '@/lib/borsa-italiana/dividend-scraper';
import { getFxRates, normalizePriceToEur } from '@/lib/fx-rates';

/**
 * POST /api/dividends/scrape
 *
 * Scarica storico dividendi da Borsa Italiana per un ISIN e li persiste
 * nel DB dell'utente. Applica la ritenuta italiana 26%, converte in EUR
 * e salta i duplicati (unique constraint su userId+ticker+exDate+type).
 */
export async function POST(req: Request) {
    try {
        const userId = await getAuthenticatedUserId();
        const body = await req.json();
        const parsed = dividendScrapeSchema.safeParse(body);
        if (!parsed.success) {
            return NextResponse.json({ error: 'Dati non validi', details: parsed.error.issues }, { status: 400 });
        }
        const { isin, ticker, quantity, assetName, assetType, costPerShare } = parsed.data;

        const scraped = await scrapeDividendsByIsin(isin, assetType);
        if (scraped.length === 0) {
            return NextResponse.json({
                success: false,
                message: 'Nessun dividendo trovato su Borsa Italiana per questo ISIN',
                scraped: 0,
                created: 0,
                skipped: 0,
            });
        }

        const rates = await getFxRates();
        let created = 0;
        let skipped = 0;
        const createdIds: string[] = [];

        for (const div of scraped) {
            try {
                // Calculate amounts based on current quantity (manual tracking doesn't preserve historical qty)
                const grossAmount = div.dividendPerShare * quantity;
                const taxAmount = calculateDividendTax(grossAmount);
                const netAmount = grossAmount - taxAmount;

                // EUR conversion
                let grossAmountEur: number | null = null;
                let netAmountEur: number | null = null;
                let exchangeRate: number | null = null;

                if (div.currency !== 'EUR' && div.currency !== 'Unknown') {
                    grossAmountEur = normalizePriceToEur(grossAmount, div.currency, rates);
                    netAmountEur = normalizePriceToEur(netAmount, div.currency, rates);
                    exchangeRate = grossAmount > 0 ? grossAmountEur / grossAmount : null;
                }

                await prisma.dividendRecord.create({
                    data: {
                        userId,
                        assetTicker: ticker,
                        assetIsin: isin.toUpperCase(),
                        assetName: assetName ?? null,
                        exDate: div.exDate,
                        paymentDate: div.paymentDate,
                        dividendPerShare: div.dividendPerShare,
                        quantity,
                        grossAmount,
                        taxAmount,
                        netAmount,
                        currency: div.currency === 'Unknown' ? 'EUR' : div.currency,
                        grossAmountEur,
                        netAmountEur,
                        exchangeRate,
                        dividendType: div.dividendType,
                        isAutoGenerated: true,
                        costPerShare: costPerShare ?? null,
                        notes: `Scaricato da Borsa Italiana`,
                    },
                });
                created++;
            } catch (err) {
                // Duplicate (P2002) or other error: skip
                if (err && typeof err === 'object' && 'code' in err && err.code === 'P2002') {
                    skipped++;
                } else {
                    console.warn(`Scrape create failed for ${ticker} ${div.exDate}:`, err);
                    skipped++;
                }
            }
        }

        return NextResponse.json({
            success: true,
            message: `Elaborati ${scraped.length} dividendi: ${created} nuovi, ${skipped} già presenti`,
            scraped: scraped.length,
            created,
            skipped,
            createdIds,
            taxRate: IT_DIVIDEND_WITHHOLDING_TAX,
        });
    } catch (err) {
        if (err instanceof UnauthorizedError) return unauthorizedResponse();
        console.error('POST /api/dividends/scrape error:', err);
        return NextResponse.json({ error: 'Errore interno' }, { status: 500 });
    }
}
