-- CreateTable
CREATE TABLE "AssistantThread" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "title" TEXT NOT NULL DEFAULT 'Nuova conversazione',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "AssistantThread_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "AssistantMessage" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "threadId" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "toolTrace" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AssistantMessage_threadId_fkey" FOREIGN KEY ("threadId") REFERENCES "AssistantThread" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "AssistantMemory" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "fact" TEXT NOT NULL,
    "pinned" BOOLEAN NOT NULL DEFAULT false,
    "source" TEXT NOT NULL DEFAULT 'auto',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "AssistantMemory_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "DividendRecord" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "assetTicker" TEXT NOT NULL,
    "assetIsin" TEXT,
    "assetName" TEXT,
    "exDate" TEXT NOT NULL,
    "paymentDate" TEXT NOT NULL,
    "dividendPerShare" REAL NOT NULL,
    "quantity" REAL NOT NULL,
    "grossAmount" REAL NOT NULL,
    "taxAmount" REAL NOT NULL DEFAULT 0,
    "netAmount" REAL NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'EUR',
    "grossAmountEur" REAL,
    "netAmountEur" REAL,
    "exchangeRate" REAL,
    "dividendType" TEXT NOT NULL DEFAULT 'ordinary',
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "costPerShare" REAL,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "DividendRecord_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE INDEX "AssistantThread_userId_updatedAt_idx" ON "AssistantThread"("userId", "updatedAt");

-- CreateIndex
CREATE INDEX "AssistantMessage_threadId_createdAt_idx" ON "AssistantMessage"("threadId", "createdAt");

-- CreateIndex
CREATE INDEX "AssistantMemory_userId_category_idx" ON "AssistantMemory"("userId", "category");

-- CreateIndex
CREATE INDEX "AssistantMemory_userId_pinned_idx" ON "AssistantMemory"("userId", "pinned");

-- CreateIndex
CREATE INDEX "DividendRecord_userId_paymentDate_idx" ON "DividendRecord"("userId", "paymentDate");

-- CreateIndex
CREATE INDEX "DividendRecord_userId_assetTicker_idx" ON "DividendRecord"("userId", "assetTicker");

-- CreateIndex
CREATE UNIQUE INDEX "DividendRecord_userId_assetTicker_exDate_dividendType_key" ON "DividendRecord"("userId", "assetTicker", "exDate", "dividendType");
