import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { getAuthenticatedUserId, unauthorizedResponse, UnauthorizedError } from '@/lib/api-auth';
import { dividendCreateSchema } from '@/lib/validations/dividends';

/** GET /api/dividends?ticker=XXX&from=YYYY-MM-DD&to=YYYY-MM-DD */
export async function GET(req: Request) {
    try {
        const userId = await getAuthenticatedUserId();
        const { searchParams } = new URL(req.url);
        const ticker = searchParams.get('ticker');
        const from = searchParams.get('from');
        const to = searchParams.get('to');

        const dividends = await prisma.dividendRecord.findMany({
            where: {
                userId,
                ...(ticker ? { assetTicker: ticker } : {}),
                ...(from || to
                    ? {
                          paymentDate: {
                              ...(from ? { gte: from } : {}),
                              ...(to ? { lte: to } : {}),
                          },
                      }
                    : {}),
            },
            orderBy: { paymentDate: 'desc' },
        });

        return NextResponse.json({ dividends });
    } catch (err) {
        if (err instanceof UnauthorizedError) return unauthorizedResponse();
        console.error('GET /api/dividends error:', err);
        return NextResponse.json({ error: 'Errore interno' }, { status: 500 });
    }
}

/** POST /api/dividends — create manual dividend */
export async function POST(req: Request) {
    try {
        const userId = await getAuthenticatedUserId();
        const body = await req.json();
        const parsed = dividendCreateSchema.safeParse(body);
        if (!parsed.success) {
            return NextResponse.json({ error: 'Dati non validi', details: parsed.error.issues }, { status: 400 });
        }
        const data = parsed.data;

        const created = await prisma.dividendRecord.create({
            data: {
                userId,
                assetTicker: data.assetTicker,
                assetIsin: data.assetIsin ?? null,
                assetName: data.assetName ?? null,
                exDate: data.exDate,
                paymentDate: data.paymentDate,
                dividendPerShare: data.dividendPerShare,
                quantity: data.quantity,
                grossAmount: data.grossAmount,
                taxAmount: data.taxAmount,
                netAmount: data.netAmount,
                currency: data.currency,
                grossAmountEur: data.grossAmountEur ?? null,
                netAmountEur: data.netAmountEur ?? null,
                exchangeRate: data.exchangeRate ?? null,
                dividendType: data.dividendType,
                isAutoGenerated: data.isAutoGenerated,
                costPerShare: data.costPerShare ?? null,
                notes: data.notes ?? null,
            },
        });

        return NextResponse.json({ dividend: created });
    } catch (err) {
        if (err instanceof UnauthorizedError) return unauthorizedResponse();
        // Unique constraint violation = duplicate
        if (err && typeof err === 'object' && 'code' in err && err.code === 'P2002') {
            return NextResponse.json({ error: 'Dividendo già registrato per questa data' }, { status: 409 });
        }
        console.error('POST /api/dividends error:', err);
        return NextResponse.json({ error: 'Errore interno' }, { status: 500 });
    }
}
